name = "math"
version = "0.1.0"
defaultTargets = ["math"]

[[lean_lib]]
name = "Math"

[[lean_exe]]
name = "math"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.17.0"
